openapi: 3.0.0
info:
  title: Payload Service API
  version: 1.0.0
paths:
  /payloads:
    get:
      summary: List all payloads
      responses:
        '200':
          description: A list of payloads
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Payload'
    post:
      summary: Create a new payload
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Payload'
      responses:
        '200':
          description: Created payload
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Payload'
  /payloads/{payload_id}:
    get:
      summary: Retrieve a payload by ID
      parameters:
        - name: payload_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: A single payload
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Payload'
        '404':
          description: Payload not found
components:
  schemas:
    Payload:
      type: object
      properties:
        id:
          type: integer
        content:
          type: string
      required:
        - id
        - content
