# coding: utf-8

"""
    Payload API

    Given a flight-segment is a Flight number, Origin, Destination and Julian day of the year, And that payload consists of Passengers, Baggage and Cargo, When this service learns (aka creates/updates) flight-segments with actual values, Then this service can predict the payload of a flight-segment.  It supports the following operations: * Browse all flight-segments (aka actual past Payloads) * Create a flight-segment with an actual payload. * Update a flight-segment with another actual payload. * Get a Payload Prediction * Delete a Flight-Segment  Forthcoming Features: * Result pagination * Security (Auth'n / Auth'z) * Timestamps for create, update, estimate * Payload Predictions constrained by the aircraft's MTOW and MLW. * Missing flight-segments (aka Payloads) are interpolated.  We will use a simple **Payload** resource representation with the following properties: * ID * Flight * Origin * Destination * JulianDayOfYear * Passengers (count) * Baggage (weight) * Cargo (weight) 

    The version of the OpenAPI document: v1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class Error(BaseModel):
    """
    Error
    """ # noqa: E501
    message: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["message"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of Error from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of Error from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "message": obj.get("message")
        })
        return _obj


